app/urls.py
from django.urls import path

from .models import Item
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

# アプリケーションのルーティング設定

urlpatterns = [
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('create/', ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('', ItemFilterView.as_view(), name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView 

# ルーティング設定
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('top/', include('app.urls')),    
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
	]

# 管理サイトの見出しを変更可能
#  タイトル；タイトルタグで使用
admin.site.site_title = 'タイトル'
#  サイト名：ログイン画面と管理画面上部の表示
admin.site.site_header = 'Django顧客管理画面'
#  メニュー：管理画面の見出し表示
admin.site.index_title = 'データベース管理メニュー'

app/models.py
from django.db import models
from users.models import User
from django.core import validators

class Dantai(models.Model):
    """
    団体マスタ定義クラス

    顧客所属の団体マスタを定義します。
    """

    name = models.CharField(
        verbose_name='団体マスタ',
        max_length=50,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

        
    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = '所属団体マスタ'
        verbose_name_plural = '所属団体マスタ'

class Item(models.Model):
    """
    データ定義クラス
      各フィールドを定義する
    参考：
    ・公式 モデルフィールドリファレンス
    https://docs.djangoproject.com/ja/3.1/ref/models/fields/
    """

    name = models.CharField(
        verbose_name='顧客名',
        max_length=20,
        blank=True,
        null=True,
    )

    name_furigana = models.CharField(
        verbose_name='フリガナ',
        max_length=20,
        blank=True,
        null=True,
        default='',
        validators=[validators.RegexValidator(
            regex=u'^[ァ-ヶ]+$',
            message='全角フリガナ20文字以内で入力して下さい',
        )]
    )

    postcode = models.CharField(
        verbose_name='郵便番号',
        max_length=7,
        blank=True,
        null=True,
        default='',
        validators=[validators.RegexValidator(
            regex=r'^[0-9]+$',
            message='半角数字7文字（ハイフン「-」無し）で入力して下さい',
        ),validators.MinLengthValidator(7)]
    )

    todofukenChoice = (
        (1, '北海道'),
        (2, '青森県'),
        (3, '岩手県'),
        (4, '宮城県'),
        (5, '秋田県'),
        (6, '山形県'),
        (7, '福島県'),
        (8, '茨城県'),
        (9, '栃木県'),
        (10, '群馬県'),
        (11, '埼玉県'),
        (12, '千葉県'),
        (13, '東京都'),
        (14, '神奈川県'),
        (15, '新潟県'),
        (16, '富山県'),
        (17, '石川県'),
        (18, '福井県'),
        (19, '山梨県'),
        (20, '長野県'),
        (21, '岐阜県'),
        (22, '静岡県'),
        (23, '愛知県'),
        (24, '三重県'),
        (25, '滋賀県'),
        (26, '京都府'),
        (27, '大阪府'),
        (28, '兵庫県'),
        (29, '奈良県'),
        (30, '和歌山県'),
        (31, '鳥取県'),
        (32, '島根県'),
        (33, '岡山県'),
        (34, '広島県'),
        (35, '山口県'),
        (36, '徳島県'),
        (37, '香川県'),
        (38, '愛媛県'),
        (39, '高知県'),
        (40, '福岡県'),
        (41, '佐賀県'),
        (42, '長崎県'),
        (43, '熊本県'),
        (44, '大分県'),
        (45, '宮崎県'),
        (46, '鹿児島県'),
        (47, '沖縄県 '),
    )

    address1 = models.IntegerField(
        verbose_name='都道府県',
        choices=todofukenChoice,
        blank=True,
        null=True,
    )

    address2 = models.CharField(
        verbose_name='市町村番地',
        max_length=40,
        blank=True,
        null=True,
    )

    address3 = models.CharField(
        verbose_name='建物名',
        max_length=40,
        blank=True,
        null=True,
    )

    email = models.EmailField(
        verbose_name='メール',
        max_length=100,
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（マスタ連動）
    Dantai = models.ForeignKey(
        Dantai,
        verbose_name='所属団体（マスタ連動）',
        blank=True,
        null=True,
        related_name='Dantai',
        on_delete=models.SET_NULL,
    ) 

    leaseDate = models.DateField(
        verbose_name='リース期限',
        blank=True,
        null=True,
    )

    onlineSupport = models.BooleanField(
        verbose_name='オンラインサポート',
    )

    hpUrl = models.URLField(
        verbose_name='HPのURL',
        max_length=100,
        blank=True,
        null=True,
    )

    memo = models.TextField(
        verbose_name='メモ',
        blank=True,
        null=True,
    )

    # # サンプル項目1 文字列
    # CustomerName = models.CharField(
    #     verbose_name='顧客名',
    #     max_length=20,
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目2 メモ
    # sample_2 = models.TextField(
    #     verbose_name='サンプル項目2 メモ',
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目3 整数
    # sample_3 = models.IntegerField(
    #     verbose_name='サンプル項目3 整数',
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目4 浮動小数点
    # sample_4 = models.FloatField(
    #     verbose_name='サンプル項目4 浮動小数点',
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目5 固定小数点
    # sample_5 = models.DecimalField(
    #     verbose_name='サンプル項目5 固定小数点',
    #     max_digits=5,
    #     decimal_places=2,
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目6 ブール値
    # sample_6 = models.BooleanField(
    #     verbose_name='サンプル項目6 ブール値',
    # )

    # # サンプル項目7 日付
    # sample_7 = models.DateField(
    #     verbose_name='サンプル項目7 日付',
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目8 日時
    # sample_8 = models.DateTimeField(
    #     verbose_name='サンプル項目8 日時',
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目9 選択肢（固定）
    # sample_9_choice = (
    #     (1, '選択１'),
    #     (2, '選択２'),
    #     (3, '選択３'),
    # )

    # sample_9 = models.IntegerField(
    #     verbose_name='サンプル項目9_選択肢（固定）',
    #     choices=sample_9_choice,
    #     blank=True,
    #     null=True,
    # )

    # # サンプル項目9 選択肢（マスタ連動）
    # sample_10 = models.ForeignKey(
    #     User,
    #     verbose_name='サンプル項目10_選択肢（マスタ連動）',
    #     blank=True,
    #     null=True,
    #     related_name='sample_10',
    #     on_delete=models.SET_NULL,
    # )

    # 以下、管理項目

    # 作成者(ユーザー)
    created_by = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='CreatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 作成日時
    created_at = models.DateTimeField(
        verbose_name='作成日時',
        blank=True,
        null=True,
        editable=False,
    )

    # 更新者(ユーザー)
    updated_by = models.ForeignKey(
        User,
        verbose_name='更新者',
        blank=True,
        null=True,
        related_name='UpdatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 更新日時
    updated_at = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        null=True,
        editable=False,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.name

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = '顧客マスタ'
        verbose_name_plural = '顧客マスタ'

app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>サンプルアプリ_base.html</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sandstone/bootstrap.min.css" integrity="sha384-zEpdAL7W11eTKeoBJK1g79kgl9qjP7g84KfK3AZsuonx38n8ad+f5ZgXtoSDxPOh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "app/css/validationEngine.jquery.css" %}" type="text/css"/>
    <link rel="stylesheet" href="{% static "app/css/app.css" %}">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light ">
    <a class="navbar-brand" href="#">顧客管理サイト画面</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">顧客管理画面</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">ログアウト</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cyborg/bootstrap.min.css" integrity="sha384-nEnU7Ae+3lD52AK+RGNzgieBWMnEfgTbRHIwEvp1XXPdqdO6uLTd/NwXbzboqjc2" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"
        charset="UTF-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ja.min.js"></script>
<script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
<script src="{% static "app/js/plugins/jquery.autoKana.js" %}"></script>
<script src="https://ajaxzip3.github.io/ajaxzip3.js" charset="UTF-8"></script>
<script src="{% static "app/js/plugins/history.js" %}"></script>
<script src="{% static "app/js/plugins/jquery.validationEngine-ja.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static "app/js/plugins/jquery.validationEngine.min.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
    <div class="container">
        <h2 class="text-center">データ削除</h2>
        <p>このデータを削除します。よろしいですか？</p>

        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-danger delete" value="削除"/>
                    </div>
                </div>
            </div>
            {% include "./item_detail_contents.html" %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right mb-3">
                        <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-danger delete" value="削除"/>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
    <div class="container">
        <h2 class="text-center">詳細表示</h2>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-outline-dark float-right" href="{% url 'index' %}">戻る</a>
            </div>
        </div>
        <!--  -->
        {% include "./item_detail_contents.html" %}

        <div class="row">
            <div class="col-12">
                <div class="float-right mt-1 mb-3">
                    <a class="btn btn-dark " href="{% url 'update' item.pk %}">編集</a>
                    <a class="btn btn-danger " href="{% url 'delete' item.pk %}">削除</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <a class="btn btn-outline-dark float-right" href="{% url 'index' %}">戻る</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/item_detail_contents.html
<div class="row">
    <div class="col-5 col-sm-3">
        <p>顧客名</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.name|default_if_none:"（未入力）"  }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>フリガナ</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.name_furigana|default_if_none:"（未入力）"  }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>郵便番号</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{item.postcode|default_if_none:"（未入力）" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>住所</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{item.get_address1_display|default_if_none:"（未入力）" }}{{item.address2|default_if_none:"" }}{{item.address3|default_if_none:"" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>メール</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.email|default_if_none:"（未入力）" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>所属団体（マスタ連動）</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.Dantai|default_if_none:"（未入力）" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>リース期限</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.leaseDate|date:"Y年m月d日" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>オンラインサポート</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.onlineSupport|yesno:"○,×" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>HPのURL</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.hpUrl|default_if_none:"（未入力）" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>メモ</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.memo|default_if_none:"（未入力）" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成日時</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新日時</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>



<div class="row">
    <div class="col-12">
        <table border="1">
            <tr>
                <th>項目名</th>
                <th>内容</th>
            </tr>
            <tr>
                <td>顧客名</td>
                <td>{{ item.name|default_if_none:"未入力" }}</td>
            </tr>
            <tr>
                <td>フリガナ</td>
                <td>{{ item.name_furigana|default_if_none:"未入力" }}</td>
            </tr>
            <tr>
                <td>郵便番号</td>
                <td>{{ item.postcode|default_if_none:"" }}</td>
            </tr>
            <tr>
                <td>住所</td>
                <td>{{ item.get_address1_display|default_if_none:"" }}{{ item.address2|default_if_none:"" }}{{ item.address3|default_if_none:"" }}</td>
            </tr>
            <tr>
                <td>メール</td>
                <td>{{ item.email|default_if_none:"" }}</td> 
            </tr>
            <tr>
                <td>所属団体</td>
                <td>{{ item.Dantai|default_if_none:"" }}</td>
            </tr>
            <tr>
                <td>リース期限</td>
                <td>{{ item.leaseDate|date:"Y年m月d日" }}</td> 
            </tr>
            <tr>
                <td>オンラインサポート</td>
                <td align="center">{{ item.onlineSupport|yesno:"○,×" }}</td>
            </tr>
            <tr>
                <td>HPのURL</td>
                <td>{{ item.hpUrl}}</td> 
            </tr>
            <tr>
                <td>メモ</td>
                <td>{{ item.memo}}</td> 
            </tr>
            <tr>
                <td>作成者</td>
                <td>{{ item.created_by.get_full_name }}</td> 
            </tr>
            <tr>
                <td>作成日時</td>
                <td>{{ item.created_at|date:"Y/m/d G:i:s" }}</td> 
            </tr>
            <tr>
                <td>更新者</td>
                <td>{{ item.updated_by.get_full_name }}</td> 
            </tr>
            <tr>
                <td>更新日時</td>
                <td>{{ item.updated_at|date:"Y/m/d G:i:s" }}</td> 
            </tr>
        </table>

    </div>
</div>

app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">検索条件</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="filter" method="get">
                        <div class="modal-body">
                             {{ filter.form|crispy }}
                        </div>
                    </form>
                    <div class="modal-footer">
                        <a class="btn btn-outline-dark" data-dismiss="modal">戻る</a>
                        <button type="submit" class="btn btn-outline-dark" form="filter">検索</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
                <div class="float-right mt-1">
                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>

        <!--
        <div class="row">
            <div class="col-12">
                <ul class="list-group">
                    {% for item in item_list %}
                        <li class="list-group-item">
                            {# item_detail_contents.html を参考に必要な項目を追加してください07 #}
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>顧客名08</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.name|default_if_none:"未入力11" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>住所09</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.address1|default_if_none:"未入力12" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>都道府県10</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{  item.get_address1_display|default_if_none:"未入力13" }}</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>オンラインサポート</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.onlineSupport|yesno:"○,×"}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>リース期限</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.leaseDate|date:"Y年m月d日"  }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>所属団体（マスタ連動）</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{  item.belongsDantai.get_full_name|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>メモ</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.memo|default_if_none:"未入力" }}</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成者</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_by.get_full_name }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成日時</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="float-right">
                                        <a class="btn btn-outline-dark " href="{% url 'detail' item.pk %}">詳細14</a>
                                        <a class="btn btn-outline-dark " href="{% url 'update' item.pk %}">編集15</a>
                                        <a class="btn btn-outline-dark " href="{% url 'delete' item.pk %}">削除16</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">
                            対象のデータがありません17
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        -->

        <div class="row">
            <div class="col-12">

                <table border="1">
                    {% if item_list %}
                    <tr>
                        <th><ruby>顧客名<rt>こきゃくめい</rt></ruby></th>
                        <th>住所</th>
                        <!--  <th>メール</th> -->
                        <!--  <th>都道府県</th> -->
                        <th>所属団体</th>
                        <!-- <th>リース期限</th> -->
                        <!-- <th>Online</th> -->
                        <!-- <th>HPのURL</th> -->
                        <!-- <th>メモ</th> -->
                        <th>詳細</th>
                        <th>編集</th>
                        <th>削除</th>
                    </tr>
                    {% endif %}

                    {% for item in item_list %}
                    <tr>
                        <td>{{ item.name|default_if_none:"未入力" }}</td>
                        <!--  <td>{{ item.address1|default_if_none:"" }}</td> -->
                        <!--  <td>{{ item.email|default_if_none:"" }}</td> -->
                        <td>{{ item.get_address1_display|default_if_none:"" }}{{ item.address2|default_if_none:"" }}</td>
                        <td>{{ item.Dantai|default_if_none:"" }}</td>
                        <!-- <td>{{ item.leaseDate|date:"Y年m月d日" }}</td> -->
                        <!-- <td align="center">{{ item.onlineSupport|yesno:"○,×" }}</td> -->
                        <!-- <td>{{ item.hpUrl|truncatechars:16}}</td> -->
                        <!-- <td>{{ item.memo|truncatechars:16}}</td> -->
                        <td  align="center"><a class="btn btn-secondary " href="{% url 'detail' item.pk %}">詳細</a></td>
                        <td  align="center"><a class="btn btn-dark " href="{% url 'update' item.pk %}">編集</a></td>
                        <td  align="center"><a class="btn btn-danger " href="{% url 'delete' item.pk %}">削除</a></td>
                    </tr>
                    {% empty %}
                        <li class="list-group-item">
                            対象のデータがありません
                        </li>
                    {% endfor %}
                </table>

            </div>
        </div>

        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right mt-1 mb-3">
                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}